### ISSUE TITLE
java.lang.NoClassDefFoundError with Modular Machinery version 1.10.0

### ISSUE THREAD

**Issue by Charnuz** [DaedalusGame/Modular-Diversity#44]
All mods are for minecraft version 1.12.2, the issue is [ComponentType.ComponentRegistryEvent was removed](https://github.com/DaedalusGame/Modular-Diversity/blob/ad803ea1041ed4e98469f0b522ac91bd3f0f909e/src/main/java/modulardiversity/Registry.java#L196).

[The current method](https://github.com/HellFirePvP/ModularMachinery/blob/04fca2051a810c924b638b653e82ac7d1b93cd76/src/main/java/hellfirepvp/modularmachinery/common/registry/internal/PrimerEventHandler.java#L67) uses the event `RegistryEvent.Register<ComponentType> event`.

**Comment by maggo1312** [comment]
Same Problem, different Version , the 1.10.0 works like expected. With Modular Machinery 1.11+ crash on startup [Crashlog](https://gist.github.com/maggo1312/0e19b3dfef8099083d878d6fb1ec4a66)

**Comment by IcedReaper** [comment]
Same issue like @maggo1312. Crashes with MM 1.11.0 and 1.11.1, but works with 1.10.0.
Same crash stack.

**Comment by MasterBuilder747** [comment]
same issue here, I guess im gonna have to downgrade for now until @DaedalusGame fixes this, or someone else...

**Comment by MasterBuilder747** [comment]
well, crap. now downgrading MM makes Modular Magic not work, so I guess for now I can only choose between modular magic and modular diversity, but I can't have both... :/

**Comment by DAmNRelentless** [comment]
Today, you released a new version and this is still not fixed...
I mean this is an addon for Modular Machinery and doesn't work with the newest version.
That's sad.

**Comment by DaedalusGame** [comment]
i didn't put in the changelog that i updated to the newest MM version did I?

**Comment by DAmNRelentless** [comment]
No you didn't and I also didn't say that but it's sad to see that this isn't fixed yet. :/

**Comment by Archilyte** [comment]
so
is it getting fixed?

**Comment by DaedalusGame** [comment]
yes

**Comment by Archilyte** [comment]
its been almost a month
MM and Modular magic are updating and i cant use the newer versions
pls do something

**Comment by Archilyte** [comment]
now its almost two months
5 since the issue started

**Comment by Archilyte** [comment]
so
are you fixing this issue or not

**Comment by Archilyte** [comment]
did u abandon this mod?

**Comment by Archilyte** [comment]
Hello?

**Comment by Archilyte** [comment]
please fix it its way too late i need this fixed so that i can use the latest version of modular magic which has nature's aura support

**Comment by TheFlash787** [comment]
@DaedalusGame When is this being fixed? It has been almost a year, and it's quite silly that a Modular Machines addon is refusing to update to the latest version of it's parent mod.

**Comment by MasterBuilder747** [comment]
wow this is still occurring?my modpack is waiting now.... i need a custom MM that can produce enough mekanism heat for a max boiler and steam turbine... :/

**Comment by Archilyte** [comment]
@DaedalusGame is accepting PRs...

**Comment by TheFlash787** [comment]
@Archilyte We can't send in PRs because this repository isn't updated with the latest version on Twitch. If that is fixed, then we could possibly think about sending one in.

**Comment by MasterBuilder747** [comment]
oh wow. He doesn't even push to his own repo? wtf

**Comment by Archilyte** [comment]
bruh

**Comment by DaedalusGame** [comment]
wait bruh

**Comment by GreyGoldFish** [comment]
I think that I'm getting the same issue.
`net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: hellfirepvp/modularmachinery/common/crafting/ComponentType$ComponentRegistryEvent`

**Comment by ChromaPIE** [comment]
It's kinda confusing. If the latest MD is incompatible with the latest MM why it's still hanging there on CurseForge without any statement of it being incompatible.

**Comment by superJK92iscool** [comment]
So it still has not been fixed

**Comment by superJK92iscool** [comment]
@DaedalusGame Can you fix it already, it has been a few years and still is broken

**Comment by DaedalusGame** [comment]
nop

**Comment by Archilyte** [comment]
lmao i got an email notification from this bruh this shits gone on for 7 years now wtf
